// <auto-generated />
using System;
using BienestarApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BienestarApi.Data.Migrations
{
    [DbContext(typeof(BienestarDbContext))]
    [Migration("20260928231510_AgregaConsentimientoYSusDetalle")]
    partial class AgregaConsentimientoYSusDetalle
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BienestarApi.Models.AlertaRiesgo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("EncuestaBasalId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<bool>("SeMostroMensajeAyuda")
                        .HasColumnType("bit");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EncuestaBasalId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("AlertasRiesgo");
                });

            modelBuilder.Entity("BienestarApi.Models.Cuenta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("UsuarioId")
                        .IsUnique();

                    b.ToTable("Cuentas");
                });

            modelBuilder.Entity("BienestarApi.Models.EncuestaBasal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Fase")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<int>("PuntajeIPAQ")
                        .HasColumnType("int");

                    b.Property<int>("PuntajePHQ9")
                        .HasColumnType("int");

                    b.Property<int>("PuntajeSISCO")
                        .HasColumnType("int");

                    b.Property<int>("RespuestaItem9")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId", "Fase")
                        .IsUnique();

                    b.ToTable("EncuestasBasal");
                });

            modelBuilder.Entity("BienestarApi.Models.EncuestaSUS", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ComentarioLoMasUtil")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("ComentarioMejoras")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("FechaAplicacion")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("PuntajeSUS")
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("RespuestasSUS")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId")
                        .IsUnique();

                    b.ToTable("EncuestasSUS");
                });

            modelBuilder.Entity("BienestarApi.Models.RegistroDiario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CalidadSueno")
                        .HasColumnType("int");

                    b.Property<int>("EstadoAnimo")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("MinutosActividadFisica")
                        .HasColumnType("int");

                    b.Property<int>("NivelEstres")
                        .HasColumnType("int");

                    b.Property<int>("TiempoId")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TiempoId");

                    b.HasIndex("UsuarioId", "TiempoId")
                        .IsUnique();

                    b.ToTable("RegistrosDiarios");
                });

            modelBuilder.Entity("BienestarApi.Models.Tiempo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Anio")
                        .HasColumnType("int");

                    b.Property<int>("DiaSemana")
                        .HasColumnType("int");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date");

                    b.Property<int>("Semana")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Fecha")
                        .IsUnique();

                    b.ToTable("DimTiempo", (string)null);
                });

            modelBuilder.Entity("BienestarApi.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Carrera")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodigoUniversitario")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("FechaAceptaConsentimiento")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VersionConsentimiento")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CodigoUniversitario")
                        .IsUnique();

                    b.ToTable("DimUsuario", (string)null);
                });

            modelBuilder.Entity("BienestarApi.Models.AlertaRiesgo", b =>
                {
                    b.HasOne("BienestarApi.Models.EncuestaBasal", "EncuestaBasal")
                        .WithMany()
                        .HasForeignKey("EncuestaBasalId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BienestarApi.Models.Usuario", "Usuario")
                        .WithMany("AlertasRiesgo")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EncuestaBasal");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("BienestarApi.Models.Cuenta", b =>
                {
                    b.HasOne("BienestarApi.Models.Usuario", "Usuario")
                        .WithOne("Cuenta")
                        .HasForeignKey("BienestarApi.Models.Cuenta", "UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("BienestarApi.Models.EncuestaBasal", b =>
                {
                    b.HasOne("BienestarApi.Models.Usuario", "Usuario")
                        .WithMany("EncuestasBasal")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("BienestarApi.Models.EncuestaSUS", b =>
                {
                    b.HasOne("BienestarApi.Models.Usuario", "Usuario")
                        .WithMany("EncuestasSUS")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("BienestarApi.Models.RegistroDiario", b =>
                {
                    b.HasOne("BienestarApi.Models.Tiempo", "Tiempo")
                        .WithMany("RegistrosDiarios")
                        .HasForeignKey("TiempoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BienestarApi.Models.Usuario", "Usuario")
                        .WithMany("RegistrosDiarios")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tiempo");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("BienestarApi.Models.Tiempo", b =>
                {
                    b.Navigation("RegistrosDiarios");
                });

            modelBuilder.Entity("BienestarApi.Models.Usuario", b =>
                {
                    b.Navigation("AlertasRiesgo");

                    b.Navigation("Cuenta");

                    b.Navigation("EncuestasBasal");

                    b.Navigation("EncuestasSUS");

                    b.Navigation("RegistrosDiarios");
                });
#pragma warning restore 612, 618
        }
    }
}
